fix(UISection): when no data is obtained, an error occurs, it is misspelled
Error:
- Failed to load resource: the server responded with a status of 403 (Forbidden)
this.sectionTitle.toLowercase is not a function

Solution:
- The js method `toLowercase` is misspelled and has been changed to `toLowerCase`.